#!/bin/bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
force=$([[ "$1" == "-y" ]] && echo "y" || echo "n")

function lnk
{
  local target="$dir/$1"
  local link="$HOME/$1"
  shift

  local confirm="y"
  if [[ -L "$link" || -f "$link" || -h "$link" ]] && [[ "$force" == "n" ]]; then
    while :; do
      echo -n "$link already exists, overwrite [Y/n]? "
      read confirm

      if [[ -z "$confirm" ]]; then
        confirm="y"
      fi
      confirm=$(echo "$confirm" | awk '{ print tolower($0) }')
      [[ "$confirm" != "y" && "$confirm" != "n" ]] || break
    done
  fi

  if [[ "$confirm" == "y" || "$force" == "y" ]]; then
    rm -rf "$link" 2> /dev/null
    ln -s "$target" "$link"
  fi
}

lnk .bash_profile
lnk .bashrc
lnk .bash_aliases
. ~/.bashrc

lnk .gitconfig

mkdir -p ~/.subversion
lnk .subversion/config

lnk .ssh
if [[ -f ~/Dropbox/.ssh/id_rsa ]]; then
  cp ~/Dropbox/.ssh/id_rsa ~/.ssh
fi

if [[ -f ~/.ssh/id_rsa ]]; then
  chmod 600 ~/.ssh/id_rsa
fi

lnk .vim
lnk .vimrc

lnk .tmux.conf

